# Generated by Django 4.0.1 on 2022-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkoutitems',
            table='CheckoutItem',
        ),
    ]
