# Generated by Django 4.0.1 on 2022-06-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo_1',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo_2',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo_3',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo_4',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
    ]
