# Generated by Django 4.0.1 on 2022-07-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashdevlivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=50)),
                ('lastname', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(db_index=True, max_length=50)),
                ('contact', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='grandTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='number_of_products',
            field=models.IntegerField(default=1),
        ),
    ]
