# Generated by Django 4.0.1 on 2022-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_product_featured_alter_product_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin',
            field=models.BooleanField(default=False),
        ),
    ]
