# Generated by Django 4.0.1 on 2022-06-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_media_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
