# Generated by Django 4.0.1 on 2022-07-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_cashdevlivery'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashdevlivery',
            table=None,
        ),
    ]
