# Generated by Django 4.0.1 on 2022-07-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_checkoutitems_table'),
        ('Home', '0003_cashdevlivery_cart_grandtotal_and_more'),
        ('Home', '0004_alter_product_featured_alter_product_medicine_and_more'),
        ('Home', '0005_alter_cashdevlivery_table'),
    ]

    operations = [
    ]
