# Generated by Django 4.0.1 on 2022-07-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_merge_20220725_1203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkoutitems',
            table=None,
        ),
    ]
