# Generated by Django 4.0.1 on 2022-06-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
