# Generated by Django 4.0.1 on 2022-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_portfolio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('category', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField()),
                ('available', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('recently_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
