# Generated by Django 4.0.1 on 2022-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mediciine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='skin',
            field=models.BooleanField(default=False),
        ),
    ]
