# Generated by Django 4.0.1 on 2022-06-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_product_featured_product_mediciine_product_skin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
