# Generated by Django 4.0.1 on 2022-06-21 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mediciine',
            new_name='is_mediciine',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='recently_viewed',
            new_name='is_recently_viewed',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='skin',
            new_name='is_skin',
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
