# Generated by Django 4.0.1 on 2022-06-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rename_featured_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_mediciine',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_recently_viewed',
            new_name='recently_viewed',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_skin',
            new_name='skin',
        ),
    ]
