# Generated by Django 4.0.1 on 2022-06-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rename_featured_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_mediciine',
        ),
        migrations.AddField(
            model_name='product',
            name='is_medicine',
            field=models.BooleanField(default=False),
        ),
    ]
